// --------------------------------------------------------
// Auto-generated by SoundNamesGenerator
// DO NOT EDIT MANUALLY!
// --------------------------------------------------------

public static class SoundNames
{
    public const string Boop = "boop";

}